### ISSUE TITLE
Making the navbar Responsive and making a cleaner navbar

### ISSUE THREAD

**Issue by shreyabajaj12** [GarimaSingh0109/WasteManagment#139]
I would like to make navbar responsive so that it could adapt to all size of the screen .
Putting the logo at the right page and enhancing the user interface.
I want you to assign me this issue.
![Screenshot 2024-10-05 141813](https://github.com/user-attachments/assets/c7485617-f722-4acc-b8fb-50fc9124f1c0)

**Comment by Mkmihir16** [comment]
I am interested in this issue.please assign me this issue.
