### ISSUE TITLE
 Community section 

### ISSUE THREAD

**Issue by Lekkhasri** [GarimaSingh0109/WasteManagment#171]
### Description

The Community engagement don't have any button to join the any existing community page .
The commitment to sustainability is below the sign up and login which i like to be next to the community engagement .
can you assign the issue to me. @GarimaSingh0109 
![Screenshot 2024-10-06 125033](https://github.com/user-attachments/assets/c8af2a7a-3641-4d84-b428-f1a06026b991)
![Screenshot 2024-10-06 124333](https://github.com/user-attachments/assets/bfd4ec74-21ce-458c-b768-a4ecce1c946d)
![Screenshot 2024-10-06 125404](https://github.com/user-attachments/assets/3b04586e-fd46-4c59-aa66-27570c14ee36)

### Steps to Reproduce

![Screenshot 2024-10-06 130203](https://github.com/user-attachments/assets/df9e1a6d-f074-4cf8-b045-a820acb3479f)
![Screenshot 2024-10-06 130415](https://github.com/user-attachments/assets/f29e0335-ce2a-4101-b203-89dc112f996b)

### Expected Behavior

The Join community engagements should have button to join the existing community.

The our commitment to sustainability can have some images and below the community engagements.

### Actual Behavior

There is no button to join it . The our commitment to sustainability is below the sign up pages and dont have any images.

### Additional Information

There is no any other information about it

### Browser

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file)
- [X] The changes don't break the code
- [X] Please attach screenshots and videos of the development work once done

**Comment by Aryam2121** [comment]
i am interested  to work on this Branch and please assign to me and i update the Signup.html and you have to review and merge that branch also and close the issue as soon as Possible

**Comment by Lekkhasri** [comment]
@Aryam2121 I am currently working on this I will complete the issue within today night

**Comment by Aryam2121** [comment]
However, it is up to the author to decide which branch should be merged and which should not.
