### ISSUE TITLE
The Sign Up Page

### ISSUE THREAD

**Issue by Lekkhasri** [GarimaSingh0109/WasteManagment#172]
### Issue Description

The sign up section is with in the index.html file if it was in another page it would be nice.

### Screenshots or Examples (if applicable)

1. The Sign Up page in waste management looks like this
2. ![image](https://github.com/user-attachments/assets/ef18ca58-b08a-4feb-9a23-d11551150676)

### Proposed Solution (optional)

By creating another login and sign up page the website looks very clean. 
We can also add additional options like continue with google .
Can you assign the issue to me. @GarimaSingh0109 

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] The changes don't break the code.
- [X] Please attach the screenshots and video of the development work once it is done.

**Comment by khushi-joshi-05** [comment]
@Lekkhasri i have assigned u the issue.

**Comment by Lekkhasri** [comment]
@khushi-joshi-05  Can you assign the labels please
