### ISSUE TITLE
[BUG] <Footer Text not visible>

### ISSUE THREAD

**Issue by jayashisbarua** [GarimaSingh0109/WasteManagment#176]
### Description

The text color is blending with the background colour of footer , so I would like to fix this issue and make it more user friendly abd easy to use. Can you please assign this to me under gssoc and hacktoberfest. I would love to contribute in this project. 
Thank you
<h2> Issue Screenshot </h2>
<img width="1469" alt="Screenshot 2024-10-06 at 6 45 05 PM" src="https://github.com/user-attachments/assets/5dd519ac-f75a-4866-94b7-90c98de1f043">

### Steps to Reproduce

1. changing the colour of text
2. making it not blend with bg colour

### Expected Behavior

The text should be clearly visible in eyes and easy to catch.

### Actual Behavior

Text not visible , text color getting merged with background colour

### Browser

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file)
- [X] The changes don't break the code
- [X] Please attach screenshots and videos of the development work once done

**Comment by khushi-joshi-05** [comment]
@jayashisbarua i have assigned u the issue.

**Comment by jayashisbarua** [comment]
@khushi-joshi-05 okay, thank you

**Comment by jayashisbarua** [comment]
@khushi-joshi-05 I am not able to clone the repo in my local desktop, Please can you help?

**Comment by jayashisbarua** [comment]
@khushi-joshi-05 I have Pulled requested this issue in-
https://github.com/GarimaSingh0109/Resum-Resume/pull/389
please check that.
