### ISSUE TITLE
[DOCS] <write your suggestion here>"Added CONTRIBUTING.md and Updated README.md for Contributor Guidelines"

### ISSUE THREAD

**Issue by Varsha567** [GarimaSingh0109/WasteManagment#193]
### Issue Description

Added a CONTRIBUTING.md file to provide clear guidelines for contributors, including steps for setting up, branching, and making pull requests.
Updated the README.md to include a reference to the new contribution guidelines, and modified the project structure section accordingly.

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] The changes don't break the code.
- [X] Please attach the screenshots and video of the development work once it is done.

### Additional Comments (optional)

could you please assign this to me?

**Comment by Anujyadav0074** [comment]
also add the label for GSSOC 2024 Extended please before accepting the changes
