### ISSUE TITLE
Add README.md file

### ISSUE THREAD

**Issue by Nandini-13** [GarimaSingh0109/WasteManagment#2]
Issue: No README.md file
Description: CONTRIBUTING.md file should be added to the project to guide developers on how to contribute effectively. This file should include:

1. Steps to fork the repository
2. Instructions for setting up the development environment
3. Guidelines for submitting issues and pull requests
4. Coding style and best practices
5. Information on how to run tests (if applicable)
6. Code of conduct for contributors

Kindly assign this issue to me with the gssoc-extd label so that I can start working on it.

**Comment by Muskan-bhatt249** [comment]
@Nandini-13 Please assign me this issue, if this is a part of GSSoC-Ext

**Comment by GarimaSingh0109** [comment]
@Nandini-13 @Muskan-bhatt249 this issue has already been done by someone else look for some new issue

**Comment by Anujyadav0074** [comment]
i did this issue but i want to say i asked to tag it under gssoc and that  did not happen
