### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by Codewithmeowmeow** [GarimaSingh0109/WasteManagment#21]
upload and choose file button looks tacky, i would like to style it.
![20241001_231327](https://github.com/user-attachments/assets/df548d32-64a5-449e-bd56-3e8671480398)

**Comment by Codewithmeowmeow** [comment]
I have added css to the button. Kindly suggest changes if u want me to change it
![Uploading 17278052930247435251401457316817.jpg…]()

**Comment by Codewithmeowmeow** [comment]
I have added css to the button .
![20241001_232713](https://github.com/user-attachments/assets/2a12cd5a-f27a-42a5-8643-bb71103d254f)

**Comment by ShaikHafiza** [comment]
I would like to work on this.
