### ISSUE TITLE
[Feature] Improve UI of Sign-Up Form and Modularize for Better Usability

### ISSUE THREAD

**Issue by kavya410004** [GarimaSingh0109/WasteManagment#211]
### Description

The current sign-up form section is not user-friendly and lacks an intuitive design. To enhance the user experience, I propose improving the UI and transitioning the sign-up form to a dedicated page. This change will not only make the interface more appealing but also pave the way for better implementation of the sign-up and login backend functionalities in the future.
### Current form:
- This form is not aligned correctly which makes it hard for user to view and enter into fields.
- There is no separation from this form to surrounding sections which is not user friendly.

### Motivation

- **User Experience:** A clean and well-structured sign-up page will lead to a smoother registration process, encouraging more users to complete the sign-up.
- **Modularity:** By shifting the sign-up form to a separate page, we can create a more modular architecture. This change will simplify the integration of backend functionalities for user authentication.
- **Navigation Improvement:** Redirecting users to a dedicated sign-up page upon clicking the sign-up option in the navigation bar will streamline the user journey and reduce confusion.

### Screenshots

Current Sign up form:
![image](https://github.com/user-attachments/assets/55034330-0caa-4918-b642-8e4698ba8cfe)

### Additional Context

I will create a sign up page separately similar to the below image with signup and login options instead of farmer and buyer.
![image](https://github.com/user-attachments/assets/79df85d4-f59d-406d-b0ce-819e500b426c)

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file).
- [X] The changes don't break the code.
- [X] I will attach screenshots and videos of the development work once it is done.

### Priority

High

**Comment by kavya410004** [comment]
@GarimaSingh0109 I will work on this issue, please assign this to me.

**Comment by GarimaSingh0109** [comment]
@kavya410004 start working on it follow the color pallet

**Comment by kavya410004** [comment]
> @kavya410004 start working on it follow the color pallet

Okay, I will start working on it. Please assign this issue to me along with labels when you have time.
Thank you.

**Comment by kavya410004** [comment]
@GarimaSingh0109 I have worked on it as you said and created a pr. Could you check my pr and assign labels to it? The pull request is #217
