### ISSUE TITLE
[BUG]  Navbar Height Excess and Menu Overflow Caused by Logo Size

### ISSUE THREAD

**Issue by snehhhcodes** [GarimaSingh0109/WasteManagment#249]
### Description

The navbar's height has increased significantly due to the logo size, causing the menu items to overflow outside of the navbar. This leads to a misaligned layout and affects usability.

### Steps to Reproduce

1. Open the Index File: Access the index.html file in your project.
2. Start a Live Server: Launch a live server to view the webpage.
3. Inspect the Navbar: Look for the navbar section containing the logo and menu items.
4. Check Logo Size: Observe the logo size and its effect on the navbar height.

### Expected Behavior

The logo should be sized appropriately to prevent the navbar from expanding and causing menu overflow.

### Actual Behavior

The navbar's height is excessively increased because of the oversized logo, causing the navigation links to become misaligned and overflow outside the navbar. This results in an unbalanced layout, particularly on smaller screens, where menu items may be cut off or hidden, leading to a poor user experience.

### Additional Information

![Screenshot 2024-10-10 074158](https://github.com/user-attachments/assets/6062af13-93f2-4b72-bc61-42d70100688b)

### Browser

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file)
- [X] The changes don't break the code
- [X] Please attach screenshots and videos of the development work once done

**Comment by snehhhcodes** [comment]
@GarimaSingh0109 please assign it to me if suitable

**Comment by Iampratyush004** [comment]
@GarimaSingh0109 please assign this task to me. I have a ready code . Please assign so that i can PR
