### ISSUE TITLE
Issue Title: [Feature Request]: Add Animated Buttons to Navbar for Improved User Experience

### ISSUE THREAD

**Issue by sahhoArjun097** [GarimaSingh0109/WasteManagment#258]
### Description

This feature request aims to enhance the visual appeal and interactivity of the Waste Management project's navigation bar by introducing animated buttons. The current navbar is functional but lacks dynamic elements that could make it more attractive and engaging for users.

### Motivation

-Improved user experience with a more interactive and visually appealing navigation.
-Enhanced modern design that aligns with current web standards and user expectations.
-Potential for increased user engagement due to the polished look and feel of the navbar.

### Screenshots

![Screenshot 2024-10-10 195719](https://github.com/user-attachments/assets/cdfacd55-abc7-4bee-9c6e-941305581091)

### Additional Context

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant anf lvl.

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file).
- [X] The changes don't break the code.
- [X] I will attach screenshots and videos of the development work once it is done.

### Priority

High

**Comment by Riddhi12349** [comment]
Hi please assign me this issue

**Comment by rakhiiprajapati** [comment]
hello sir please assign me this issue i am chaneing the navbar issue
