### ISSUE TITLE
Design Upload image section 

### ISSUE THREAD

**Issue by sahhoArjun097** [GarimaSingh0109/WasteManagment#26]
i can design upload image section.
![Screenshot 2024-10-01 232702](https://github.com/user-attachments/assets/53485d6e-e8c0-442b-a2e4-f53ff73bb814)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant .

**Comment by Ishika-codeit** [comment]
hey assign this to me...i try my best to improve it by mine frontend skills
thank you!!
