### ISSUE TITLE
[Feature]  Themed Redesign for Sign-Up Page

### ISSUE THREAD

**Issue by sahhoArjun097** [GarimaSingh0109/WasteManagment#270]
### Description

The current sign-up page in the Waste Management project looks quite simple and lacks a cohesive theme. A more visually appealing, themed design would enhance user engagement and create a more polished, professional look for the site. This request proposes to redesign the sign-up page with a modern, attractive theme that aligns with the overall brand of the project.

### Motivation

The sign-up page should feature a cohesive theme that complements the overall design of the project.
Implement modern UI elements such as smooth animations, visually attractive forms, and themed buttons to provide a more dynamic user experience.
The page should be responsive and accessible across all devices.

### Screenshots

![Screenshot 2024-10-11 171918](https://github.com/user-attachments/assets/70b66033-135d-4dae-aba5-dd4cae574bf4)

### Additional Context

PLease assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant . 

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file).
- [X] The changes don't break the code.
- [X] I will attach screenshots and videos of the development work once it is done.

### Priority

Low

**Comment by AK261102** [comment]
@GarimaSingh0109 please assign me
