### ISSUE TITLE
Good looking navbar

### ISSUE THREAD

**Issue by Jerusha547** [GarimaSingh0109/WasteManagment#281]
### Description

The current navbar is large and it is overlapping with the main content. I want to fix this.

### Steps to Reproduce

 I will make navbar look good and i will make sure the navbar not to overlap with the content of the pages.

### Expected Behavior

Navbar is expected not to overlap with the main content

### Actual Behavior

Navbar is overlapping with the main content

### Browser

Microsoft Edge

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file)
- [X] The changes don't break the code
- [X] Please attach screenshots and videos of the development work once done

**Comment by arpit74170** [comment]
please Give this task to me i will fix it
