### ISSUE TITLE
Adding Contributors page

### ISSUE THREAD

**Issue by TBorundia** [GarimaSingh0109/WasteManagment#282]
### Description

I can add the option to navigate contributor page.
I will show the github profile of all the contributors worked for the project.
I will ensure to make the page UI similar to the theme and also responsive for all screens.
It will directly fetch the data from the repository.

### Motivation

It will show,
Transparency: It shows transparency in the project's development and highlights the collaborative effort behind it.
Engagement: It helps build a community by encouraging more people to contribute and get involved.
Networking: It provides an opportunity for users to connect with contributors, potentially leading to more collaboration and support.

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file).
- [X] The changes don't break the code.
- [X] I will attach screenshots and videos of the development work once it is done.

### Priority

High

**Comment by ExPl0iT-29** [comment]
Hey,
I can do this task, can you assign this to me.
Thankyou!
