### ISSUE TITLE
Homepage is not good looking. It need some styling to look better.

### ISSUE THREAD

**Issue by DeveloperKeshavKumar** [GarimaSingh0109/WasteManagment#302]
### Description

I visited the deployment at https://garimasingh0109.github.io/WasteManagment, and found that the UI is not much pretty. I wanted to contribute this project by adding the styles to make the homepage look better. 

The full page preview is added below for reference:
![wastemgmtwebsite](https://github.com/user-attachments/assets/ed46a4b8-8a92-4d4b-902f-4bf77639630e)

### Steps to Reproduce

1. Visit the deployment at https://garimasingh0109.github.io/WasteManagment
2. See the UI.

### Expected Behavior

1. The navbar should have small height. 
2. Hero section must be visible clearly with no overlap with navbar.
3. Each section must be clearly visible in terms of UI so that visitor can distinguish between different sections.
4. The feedback and signup form should have some styling.
5. Footer must be easily distinguishable.

### Actual Behavior

1. The navbar is taking almost 20% of viewport. 
2. Hero section is overlapping under navbar.
3. Not able to differentaiate when the one section ends and another starts.
4. The feedback and signup form have no styling
5. Footer have same styles as of main content hence unable to differentiate it.

### Browser

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file)
- [X] The changes don't break the code
- [X] Please attach screenshots and videos of the development work once done

**Comment by DeveloperKeshavKumar** [comment]
@GarimaSingh0109 Kindly assign this task to me. I assure you'd like the changes done by me in the homepage of this project. And please add labels like gssoc-ext and hacktoberfest-accecpted to this issue.

**Comment by notnotkeshav** [comment]
no response from the owner of repository
