### ISSUE TITLE
[Feature]  OUR mission Section can be designed

### ISSUE THREAD

**Issue by sahhoArjun097** [GarimaSingh0109/WasteManagment#331]
### Description

our mission section need to be design i can make that section responsive , provide animation hover effect and place item in proper format

### Motivation

TO make the UI of the section similar to the website

### Screenshots

![image](https://github.com/user-attachments/assets/1cbeaee2-30f2-4692-b614-eb629e0a90aa)

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file).
- [X] The changes don't break the code.
- [X] I will attach screenshots and videos of the development work once it is done.

### Priority

High

**Comment by GarimaSingh0109** [comment]
@sahhoArjun097 can you add pointers or symbols to the points

**Comment by sahhoArjun097** [comment]
adding pointers and symbols yes i can do this , i will show some  suggestion in discord
