### ISSUE TITLE
[Feature] Add a proper footer

### ISSUE THREAD

**Issue by NK-Works** [GarimaSingh0109/WasteManagment#343]
### Description

Add a proper footer for the website

### Motivation

Current footer is basically non-existent

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file).
- [X] The changes don't break the code.
- [X] I will attach screenshots and videos of the development work once it is done.

### Priority

Low

**Comment by pameladeysarkar2003** [comment]
@GarimaSingh0109 kindly please assign the task to me i can contribute to it
