### ISSUE TITLE
[Feature] : Adding animeted Pre Loader

### ISSUE THREAD

**Issue by AbhijitMotekar99** [GarimaSingh0109/WasteManagment#347]
### Description

The new feature is an animated preloader that would display while the website is loading its contents. The preloader would help enhance user experience by providing a smooth and visually appealing loading indicator before the main content of the site is fully rendered.

### Motivation

1. Initial Load Times: Users might experience slight delays due to larger assets or slow networks. The preloader would fill this gap, making the waiting time feel more fluid and professional.
2. First-Time Users: First-time users of the site may have slower load times as assets like images and scripts are fetched for the first time. The preloader would reassure them that content is being loaded.

### Screenshots

https://github.com/user-attachments/assets/ab4e1fc8-54e5-4c2f-b58a-db67299b32af

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/WasteManagment/issues).
- [X] I have read the [Code Of Conduct](https://github.com/GarimaSingh0109/WasteManagment?tab=coc-ov-file).
- [X] The changes don't break the code.
- [X] I will attach screenshots and videos of the development work once it is done.

### Priority

High

**Comment by khushi-joshi-05** [comment]
@AbhijitMotekar99 u can start working on it.
