### ISSUE TITLE
Add a fixed navigation bar and scroll progress bar.

### ISSUE THREAD

**Issue by Rajankit26** [GarimaSingh0109/WasteManagment#37]
Hello there ! @GarimaSingh0109 

There are two improvements that I would like to suggest to enhance the user experience:
         1. Fixed Navigation Bar: The navigation bar should remain visible at the top of the 
           page when scrolling, ensuring easy access to different sections.
        2. Scroll Progress Bar: A horizontal progress bar should be added at the top of the 
            page, which fills as the user scrolls down, visually indicating how much of the page 
            has been viewed.

Current Behavior:
       1. The navigation bar is not fixed, meaning it scrolls out of view as the user moves 
           down the page.
       2.  There is no indicator showing the user's scroll progress.
     
Expected Behavior After Changes:
       1. The navigation bar will stay in place at the top of the screen as the user scrolls, making navigation easier.
       2. A progress bar will smoothly fill from left to right as the user scrolls down the page, giving visual feedback on the 
       amount of content viewed.

"I would like to take on this issue as part of GSSoC'24 Extd. Kindly assign it to me. Looking forward to your response!"
            

https://github.com/user-attachments/assets/caf26b9c-728b-4399-9d5c-f0a93c72108a

**Comment by GarimaSingh0109** [comment]
@Rajankit26 you can start working on it
