### ISSUE TITLE
I want to add an auto scroll process bar on the top also an toggle switch to for theme

### ISSUE THREAD

**Issue by STDYGIT** [GarimaSingh0109/WasteManagment#39]
Hello @GarimaSingh0109 

I’d love to help make your website even cooler by adding a futuristic touch! I can integrate a scroll progress bar and a smooth dark-to-light (and vice versa) theme toggle switch for a modern, dynamic design. It would be a pleasure to contribute these features to your website and enhance the user experience.

Looking forward to collaborating!

**Comment by STDYGIT** [comment]
I’d love to implement these modifications! Could you please assign this task to me under the GSSoC and Hacktober-fest tags? It would be great to contribute through these initiatives!

**Comment by GarimaSingh0109** [comment]
@STDYGIT i am assigning you the issue please stick to the color theme mentioned in readme file

**Comment by STDYGIT** [comment]
Closes #39
