### ISSUE TITLE
Improve Navbar and Center 'Our Features' Section

### ISSUE THREAD

**Issue by satyam1024** [GarimaSingh0109/WasteManagment#4]
Description: There are two UI improvements that I would like to suggest for the current project:

Navbar Alignment:
The "Waste Management" title in the navbar is currently positioned above the other menu items ("Upload", "Features", "Feedback", and "Contact").
I would like to align the "Waste Management" title next to these items, maintaining a cleaner and more cohesive navbar structure.
Center 'Our Features' Section:

The "Our Features" section currently appears left-aligned. To improve visual balance, I would like to center this section horizontally on the page if acceptable i would like to do this for other sections too.

Expected Behavior:
The navbar should display all items in one row, with "Waste Management" positioned before or next to the other menu items.
The "Our Features" section should be centrally aligned, with its content neatly centered in the available space.
Screenshots:
![Screenshot (2989)](https://github.com/user-attachments/assets/0a6bf52a-39cb-4059-b113-a2cbd2980087)

**Comment by satyam1024** [comment]
please assign this issue to me

**Comment by satyam1024** [comment]
Hi GarimaSingh0109
I have worked on the issue and  made the necessary changes .Here's a screenshot of the updated section for your review:

![Screenshot (2993)](https://github.com/user-attachments/assets/11a466e7-66d3-4d8c-b037-9b3d1661bf59)

Please let me know if everything looks good, or if there are any further changes you'd like me to make  like aligning other sections ,before I proceed with creating a pull request.

Thanks!

Make sure to replace [Overseer's Name] with the actual name of the overseer and provide the screenshot link in place of link_to_screenshot.

You can then submit this comment in the issue discussion.

**Comment by AkanshaOP** [comment]
I would like to work on it.please assign it to me.
