### ISSUE TITLE
Remodify the contact us Page 

### ISSUE THREAD

**Issue by SadeeshaJayaweera** [GarimaSingh0109/WasteManagment#44]
hi @GarimaSingh0109, 
I would like to revamp your contact us page and fully change the contact form which is not within the web standards. Please do assign this issue under hacktoberfest2024. 

Thank You

**Comment by KrishnaMohanty08** [comment]
I would like to improve the contact form by enhancing UI and creating concerns about the problem and why should they contact, making it more attractive 
could you please assign me the project 
1. create difference between footer and contact block
2. add more fields
3. enhance UI

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc-ext and hacktoberfest label..

**Comment by SadeeshaJayaweera** [comment]
The Code Has been Pulled and the issue is resolved.
