### ISSUE TITLE
Improve Landing Page UI

### ISSUE THREAD

**Issue by Nandini-13** [GarimaSingh0109/WasteManagment#5]
Current Landing Page is a bit basic and its UI can be made better by adding a background image and using a better font

![1](https://github.com/user-attachments/assets/6771b059-7226-478e-adc8-a55098fb6352)

Kindly assign this issue to me so that I can start working on it.

**Comment by GarimaSingh0109** [comment]
@Nandini-13 i would like you to keep same color combination 
you can refer to this color pallet for your help [https://coolors.co/palette/22577a-38a3a5-57cc99-80ed99-c7f9cc]
