### ISSUE TITLE
Enhance Feedback Form 

### ISSUE THREAD

**Issue by aditiverma-21** [GarimaSingh0109/WasteManagment#52]
![image](https://github.com/user-attachments/assets/b9127bd0-6a18-4b38-9793-5100d55fe3e7)
I can fix the feedback form using the change in colour palate for more attractive and responsive Ui .
![image](https://github.com/user-attachments/assets/5e12d7b1-1e5c-439c-97c2-0497569cf0d5)

**Comment by KrishnaMohanty08** [comment]
I would like to improve the feedback form by simplifying and giving more clarity to the user , making it more attractive 
could you please assign me the project .......I earlier i had work on similar task
