### ISSUE TITLE
Creating rate us feature

### ISSUE THREAD

**Issue by Codewithmeowmeow** [GarimaSingh0109/WasteManagment#7]
I would like to add rate us feature in this website.
Kindly close this req if u find my work appropriate

**Comment by Charul00** [comment]
i liked it  can i work on this

**Comment by Codewithmeowmeow** [comment]
Is this okay? Or should i add more features or styles?
![Uploading 20241001_230552.jpg…]()

**Comment by Codewithmeowmeow** [comment]
Added the feature kindly acknowledge. Also label it as level 1
![IMG-20241002-WA0001](https://github.com/user-attachments/assets/9bc115b2-4706-491b-941c-730ef10bab26)

**Comment by Codewithmeowmeow** [comment]
https://github.com/user-attachments/assets/a2d98643-4a46-4f13-a4e6-165488195bc6

Hey i have completed it. Kindly acknowledge
