### ISSUE TITLE
Carbon Footprint Calculator

### ISSUE THREAD

**Issue by Ketanop321** [GarimaSingh0109/WasteManagment#78]
Help users calculate their carbon footprint based on their waste habits and provide tips on how to reduce it.

**Comment by GarimaSingh0109** [comment]
@Ketanop321 start working on this issue add ss to ur pr

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc-ext and hacktoberfest label..

**Comment by Piyushsahu99** [comment]
Okay

**Comment by Codersweta7** [comment]
@GarimaSingh0109 
I want to work upon this issue 
Please assign this to me
