### ISSUE TITLE
Increase Spacing Of nav bar from right

### ISSUE THREAD

**Issue by FrankOHara43** [GarimaSingh0109/WasteManagment#85]
<h3>Description</h3>
The nav bar is hurdled towards the right side

<h3>Expected Behavior</h3>
Should be a little left

before fixing
![Screenshot 2024-10-03 191011](https://github.com/user-attachments/assets/bdf9bc1b-8cd6-4c87-8a0a-907fffb1037a)

after fixing this should look this this
![Screenshot 2024-10-03 190929](https://github.com/user-attachments/assets/24f398fa-973b-4cd5-9974-ae6911de9962)

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc-ext and hacktoberfest label..

**Comment by FrankOHara43** [comment]
some one already did it. This issue is now closed.
