### ISSUE TITLE
Updating social icons

### ISSUE THREAD

**Issue by nksmanya** [GarimaSingh0109/WasteManagment#88]
Social connections in the footer section can be hyperlinked to the respective social media icons. 
@GarimaSingh0109 I would like to work on this issue. 
Please assign this issue to me. Also assign the corresponding labels to this issue.

**Comment by SwatiSundaray** [comment]
please assign me this ,i would like to work on it

**Comment by ayushiu** [comment]
please assign this to me under Gssoc extended
